[package]
name = "compose-spec-scp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Synchronous Composability Protocol (2PC) implementation"
publish = false

[dependencies]
compose-spec.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
