[package]
name = "ethera-spec-proto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Protobuf wire types for the Ethera protocol"
publish = false

[dependencies]
ethera-spec.workspace = true
prost.workspace = true

[lints]
workspace = true
