[package]
name = "compose-spec-sbcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Superblock Construction Protocol implementation"
publish = false

[dependencies]
compose-spec.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
